language: php

php: 5.6

before_script:
    - curl -O https://download.sculpin.io/sculpin.phar
    - chmod +x sculpin.phar
    - sudo mv sculpin.phar /usr/bin/sculpin
    - composer install

script: phpunit

sudo: false
